name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix: { dir: ["bot", "config", "cf/update-activity"] }

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Verify dependencies
        run: cd ${{ matrix.dir }} && go mod verify

      - name: Build
        run: cd ${{ matrix.dir }} && go build -v ./...

      - name: Run go vet
        run: cd ${{ matrix.dir }} && go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: cd ${{ matrix.dir }} && staticcheck ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: cd ${{ matrix.dir }} && golint -set_exit_status ./...

      - name: Run tests
        run: cd ${{ matrix.dir }} && go test -v -race -vet=off ./...
