name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Verify bot dependencies
        run: cd bot && go mod verify

      - name: Verify config dependencies
        run: cd config && go mod verify

      - name: Verify cf/update-activity dependencies
        run: cd cf/update-activity && go mod verify

      - name: Build bot
        run: cd bot && go build -v ./...

      - name: Build cf/update-activity
        run: cd cf/update-activity && go build -v ./...

      - name: Run go vet on bot
        run: cd bot && go vet ./...

      - name: Run go vet on config
        run: cd config && go vet ./...

      - name: Run go vet on cf/update-activity
        run: cd cf/update-activity && go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint -set_exit_status ./...

      - name: Run bot tests
        run: cd bot && go test -v -race -vet=off ./...

      - name: Run config tests
        run: cd config && go test -v -race -vet=off ./...

      - name: Run cf/update-activity tests
        run: cd cf/update-activity && go test -v -race -vet=off ./...
